In [1]:
import numpy as np
import pandas as pd

from urllib.request import urlopen
from bs4 import BeautifulSoup as bs

import warnings
warnings.filterwarnings(action='ignore')

import matplotlib.pyplot as plt

plt.rcParams['font.family'] = 'Gulim'

In [2]:
df_confirmed_case_covid_20200120_20230831_10age = pd.read_excel('코로나바이러스감염증-19_확진환자_발생현황_230904_최종v2.xlsx', sheet_name='연령별(10세단위)')
df_confirmed_case_covid_20200120_20230831_10age

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,일자,계(명),0-9세,10-19세,20-29세,30-39세,40-49세,50-59세,60-69세,70-79세,80세이상
4,누적(명),34571873,3270242,4246913,5001095,5077644,5237457,4530938,3898743,2055996,1252845
...,...,...,...,...,...,...,...,...,...,...,...
1320,2023-08-27 00:00:00,32967,1704,4662,3647,4178,4537,4553,4871,3094,1721
1321,2023-08-28 00:00:00,13149,883,2109,1540,1889,1944,1614,1604,884,682
1322,NaN,42998,2176,7876,4933,6061,6006,5296,5156,3496,1998
1323,NaN,42586,2175,7727,5235,5820,5658,5102,5310,3278,2281
1324,NaN,49751,2673,7606,6503,7032,7032,6007,6417,3939,2542

In [3]:
df_confirmed_case_covid_20200120_20230831_10age.rename(columns = df_confirmed_case_covid_20200120_20230831_10age.iloc[3], inplace = True)
df_confirmed_case_covid_20200120_20230831_10age

,일자,계(명),0-9세,10-19세,20-29세,30-39세,40-49세,50-59세,60-69세,70-79세,80세이상
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,일자,계(명),0-9세,10-19세,20-29세,30-39세,40-49세,50-59세,60-69세,70-79세,80세이상
4,누적(명),34571873,3270242,4246913,5001095,5077644,5237457,4530938,3898743,2055996,1252845
...,...,...,...,...,...,...,...,...,...,...,...
1320,2023-08-27 00:00:00,32967,1704,4662,3647,4178,4537,4553,4871,3094,1721
1321,2023-08-28 00:00:00,13149,883,2109,1540,1889,1944,1614,1604,884,682
1322,NaN,42998,2176,7876,4933,6061,6006,5296,5156,3496,1998
1323,NaN,42586,2175,7727,5235,5820,5658,5102,5310,3278,2281
1324,NaN,49751,2673,7606,6503,7032,7032,6007,6417,3939,2542

In [4]:
df_confirmed_case_covid_20200120_20230831_10age = df_confirmed_case_covid_20200120_20230831_10age.iloc[5:, :].reset_index()
df_confirmed_case_covid_20200120_20230831_10age

,index,일자,계(명),0-9세,10-19세,20-29세,30-39세,40-49세,50-59세,60-69세,70-79세,80세이상
0,5,2020-01-20 00:00:00,1,-,-,-,1,-,-,-,-,-
1,6,2020-01-21 00:00:00,0,-,-,-,-,-,-,-,-,-
2,7,2020-01-22 00:00:00,0,-,-,-,-,-,-,-,-,-
3,8,2020-01-23 00:00:00,0,-,-,-,-,-,-,-,-,-
4,9,2020-01-24 00:00:00,1,-,-,-,-,-,1,-,-,-
...,...,...,...,...,...,...,...,...,...,...,...,...
1315,1320,2023-08-27 00:00:00,32967,1704,4662,3647,4178,4537,4553,4871,3094,1721
1316,1321,2023-08-28 00:00:00,13149,883,2109,1540,1889,1944,1614,1604,884,682
1317,1322,NaN,42998,2176,7876,4933,6061,6006,5296,5156,3496,1998
1318,1323,NaN,42586,2175,7727,5235,5820,5658,5102,5310,3278,2281
1319,1324,NaN,49751,2673,7606,6503,7032,7032,6007,6417,3939,2542

In [5]:
df_confirmed_case_covid_20200120_20230831_10age.replace(to_replace='-',value=0, inplace = True)
df_confirmed_case_covid_20200120_20230831_10age

,index,일자,계(명),0-9세,10-19세,20-29세,30-39세,40-49세,50-59세,60-69세,70-79세,80세이상
0,5,2020-01-20,1,0.0,0.0,0,1,0,0,0,0,0.0
1,6,2020-01-21,0,0.0,0.0,0,0,0,0,0,0,0.0
2,7,2020-01-22,0,0.0,0.0,0,0,0,0,0,0,0.0
3,8,2020-01-23,0,0.0,0.0,0,0,0,0,0,0,0.0
4,9,2020-01-24,1,0.0,0.0,0,0,0,1,0,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
1315,1320,2023-08-27,32967,1704.0,4662.0,3647,4178,4537,4553,4871,3094,1721.0
1316,1321,2023-08-28,13149,883.0,2109.0,1540,1889,1944,1614,1604,884,682.0
1317,1322,NaT,42998,2176.0,7876.0,4933,6061,6006,5296,5156,3496,1998.0
1318,1323,NaT,42586,2175.0,7727.0,5235,5820,5658,5102,5310,3278,2281.0
1319,1324,NaT,49751,2673.0,7606.0,6503,7032,7032,6007,6417,3939,2542.0

In [6]:
df_confirmed_case_covid_20200120_20230831_10age.loc[1317, '일자'] = '2023-08-29 00:00:00'
df_confirmed_case_covid_20200120_20230831_10age.loc[1318, '일자'] = '2023-08-30 00:00:00'
df_confirmed_case_covid_20200120_20230831_10age.loc[1319, '일자'] = '2023-08-31 00:00:00'
df_confirmed_case_covid_20200120_20230831_10age

,index,일자,계(명),0-9세,10-19세,20-29세,30-39세,40-49세,50-59세,60-69세,70-79세,80세이상
0,5,2020-01-20,1,0.0,0.0,0,1,0,0,0,0,0.0
1,6,2020-01-21,0,0.0,0.0,0,0,0,0,0,0,0.0
2,7,2020-01-22,0,0.0,0.0,0,0,0,0,0,0,0.0
3,8,2020-01-23,0,0.0,0.0,0,0,0,0,0,0,0.0
4,9,2020-01-24,1,0.0,0.0,0,0,0,1,0,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
1315,1320,2023-08-27,32967,1704.0,4662.0,3647,4178,4537,4553,4871,3094,1721.0
1316,1321,2023-08-28,13149,883.0,2109.0,1540,1889,1944,1614,1604,884,682.0
1317,1322,2023-08-29,42998,2176.0,7876.0,4933,6061,6006,5296,5156,3496,1998.0
1318,1323,2023-08-30,42586,2175.0,7727.0,5235,5820,5658,5102,5310,3278,2281.0
1319,1324,2023-08-31,49751,2673.0,7606.0,6503,7032,7032,6007,6417,3939,2542.0

In [7]:
year_month = df_confirmed_case_covid_20200120_20230831_10age.일자.astype('str').str.slice(0,7)

In [8]:
df = df_confirmed_case_covid_20200120_20230831_10age.groupby(year_month).sum()
df

,index,계(명),0-9세,10-19세,20-29세,30-39세,40-49세,50-59세,60-69세,70-79세,80세이상
일자,,,,,,,,,,,
2020-01,126,11,0.0,0.0,3,2,0,5,1,0,0.0
2020-02,899,2920,19.0,99.0,853,358,437,578,389,133,54.0
2020-03,1891,6855,94.0,416.0,1798,653,878,1266,845,518,387.0
2020-04,2745,979,27.0,76.0,297,145,112,107,113,58,44.0
2020-05,3782,703,17.0,66.0,223,134,94,83,57,16,13.0
2020-06,4575,1331,35.0,51.0,188,204,160,247,263,125,58.0
2020-07,5673,1506,54.0,74.0,258,314,249,233,185,97,42.0
2020-08,6634,5641,196.0,363.0,700,681,763,1119,1114,517,188.0
2020-09,7335,3865,136.0,161.0,442,417,485,783,814,442,185.0
2020-10,8525,2700,114.0,151.0,407,376,385,451,427,210,179.0
2020-11,9165,7688,301.0,592.0,1296,1096,1233,1347,1031,507,285.0
2020-12,10416,26523,1098.0,1720.0,3243,3346,3825,5174,4385,2145,1587.0
2021-01,11377,17470,893.0,1433.0,2235,2246,2591,3282,2644,1242,904.0
2021-02,11102,11466,637.0,829.0,1597,1732,1643,2021,1756,801,450.0
2021-03,13206,13414,749.0,978.0,1922,2131,2151,2318,1964,825,376.0
2021-04,13695,18927,913.0,1520.0,2735,2596,3061,3554,2791,1186,571.0
2021-05,15097,18329,910.0,1469.0,2884,2837,3070,3253,2515,985,406.0
2021-06,15525,16623,959.0,1346.0,3062,2780,3087,2938,1771,515,165.0
2021-07,16988,41372,2479.0,4335.0,9890,6967,7308,6810,2591,713,279.0
2021-08,17949,53073,3424.0,5541.0,12236,8925,8353,8237,4364,1364,629.0
2021-09,18285,59851,3874.0,5964.0,13556,11266,10157,7223,4982,1923,906.0
2021-10,19840,53407,4207.0,6855.0,8963,9008,7936,5822,6117,2748,1751.0
2021-11,20115,82499,7214.0,9525.0,7450,10213,9726,10338,15516,7760,4757.0
2021-12,21731,183515,20783.0,19474.0,18184,23245,24414,24350,33198,13582,6285.0
2022-01,22692,214680,25542.0,35769.0,43080,32855,33524,22340,13272,4742,3556.0
2022-02,21322,2287846,297636.0,329742.0,394189,348856,369683,257524,175967,68443,45806.0
2022-03,24521,9959370,1279285.0,1352696.0,1390640,1463168,1533008,1201246,997873,461844,279610.0
2022-04,24645,4142095,448522.0,481777.0,554366,601973,639868,546779,468720,248930,151160.0
2022-05,26412,865914,74973.0,108245.0,147723,122847,126999,114821,91553,49269,29484.0
2022-06,26475,255580,20629.0,32193.0,55015,39343,37247,32572,22896,10240,5445.0
2022-07,28303,1415963,125286.0,200684.0,260737,215638,214643,181020,126705,60949,30301.0
2022-08,29264,3469887,295667.0,372182.0,526134,496001,510309,495779,417446,229642,126727.0
2022-09,29235,1522721,130031.0,192161.0,195593,203492,223579,207778,191533,112508,66046.0
2022-10,31155,788421,54166.0,94171.0,100544,109425,116301,111750,103100,61356,37608.0
2022-11,31065,1541318,97997.0,174410.0,205416,219729,230072,221634,198906,115754,77400.0
2022-12,33046,1960579,117836.0,229013.0,268421,296395,301837,287658,242678,129443,87298.0
2023-01,34007,1117363,59399.0,96262.0,158588,171902,171203,167410,148364,85888,58347.0
2023-02,31542,337297,20601.0,28367.0,47981,52832,50101,46981,43966,26998,19470.0
2023-03,35836,307002,17760.0,45567.0,46316,45220,43444,38520,34463,21085,14627.0
2023-04,35595,353063,15503.0,36702.0,51065,56736,51145,46930,46767,29067,19148.0
2023-05,37727,533347,21431.0,61744.0,77476,83275,75658,68542,71734,44984,28503.0
2023-06,37425,508776,22743.0,59677.0,67360,78237,72981,67012,72696,43725,24345.0
2023-07,39618,989627,39774.0,122479.0,131080,145442,145700,132112,137775,86238,49027.0
2023-08,40579,1370356,56328.0,130034.0,184949,202606,198037,190991,202496,126479,78436.0

In [9]:
year = df.index.str.slice(0,4)
month = df.index.str.slice(5,7)
df['year'] = year
df['month'] = month

In [10]:
df.astype(int).head()

,index,계(명),0-9세,10-19세,20-29세,30-39세,40-49세,50-59세,60-69세,70-79세,80세이상,year,month
일자,,,,,,,,,,,,,
2020-01,126,11,0,0,3,2,0,5,1,0,0,2020,1
2020-02,899,2920,19,99,853,358,437,578,389,133,54,2020,2
2020-03,1891,6855,94,416,1798,653,878,1266,845,518,387,2020,3
2020-04,2745,979,27,76,297,145,112,107,113,58,44,2020,4
2020-05,3782,703,17,66,223,134,94,83,57,16,13,2020,5

In [11]:
df.columns

Index(['index', '계(명)', '0-9세', '10-19세', '20-29세', '30-39세', '40-49세',
       '50-59세', '60-69세', '70-79세', '80세이상', 'year', 'month'],
      dtype='object')

In [12]:
df_temp = df.reset_index()
df_temp.columns = ['일자', 'index', '계(명)', '0-9(confirmed_case)', '10-19(confirmed_case)', '20-29(confirmed_case)', '30-39(confirmed_case)', '40-49(confirmed_case)','50-59(confirmed_case)', '60-69(confirmed_case)', '70-79(confirmed_case)', 'over80(confirmed_case)', 'year', 'month']
df1=df_temp.iloc[:, 3:]
df1.columns

Index(['0-9(confirmed_case)', '10-19(confirmed_case)', '20-29(confirmed_case)',
       '30-39(confirmed_case)', '40-49(confirmed_case)',
       '50-59(confirmed_case)', '60-69(confirmed_case)',
       '70-79(confirmed_case)', 'over80(confirmed_case)', 'year', 'month'],
      dtype='object')

In [13]:

df2 = df1[['year','month', '0-9(confirmed_case)', '10-19(confirmed_case)', '20-29(confirmed_case)',
       '30-39(confirmed_case)', '40-49(confirmed_case)', '50-59(confirmed_case)',
       '60-69(confirmed_case)', '70-79(confirmed_case)', 'over80(confirmed_case)']]
df2

,year,month,0-9(confirmed_case),10-19(confirmed_case),20-29(confirmed_case),30-39(confirmed_case),40-49(confirmed_case),50-59(confirmed_case),60-69(confirmed_case),70-79(confirmed_case),over80(confirmed_case)
0,2020,01,0.0,0.0,3,2,0,5,1,0,0.0
1,2020,02,19.0,99.0,853,358,437,578,389,133,54.0
2,2020,03,94.0,416.0,1798,653,878,1266,845,518,387.0
3,2020,04,27.0,76.0,297,145,112,107,113,58,44.0
4,2020,05,17.0,66.0,223,134,94,83,57,16,13.0
5,2020,06,35.0,51.0,188,204,160,247,263,125,58.0
6,2020,07,54.0,74.0,258,314,249,233,185,97,42.0
7,2020,08,196.0,363.0,700,681,763,1119,1114,517,188.0
8,2020,09,136.0,161.0,442,417,485,783,814,442,185.0
9,2020,10,114.0,151.0,407,376,385,451,427,210,179.0
10,2020,11,301.0,592.0,1296,1096,1233,1347,1031,507,285.0
11,2020,12,1098.0,1720.0,3243,3346,3825,5174,4385,2145,1587.0
12,2021,01,893.0,1433.0,2235,2246,2591,3282,2644,1242,904.0
13,2021,02,637.0,829.0,1597,1732,1643,2021,1756,801,450.0
14,2021,03,749.0,978.0,1922,2131,2151,2318,1964,825,376.0
15,2021,04,913.0,1520.0,2735,2596,3061,3554,2791,1186,571.0
16,2021,05,910.0,1469.0,2884,2837,3070,3253,2515,985,406.0
17,2021,06,959.0,1346.0,3062,2780,3087,2938,1771,515,165.0
18,2021,07,2479.0,4335.0,9890,6967,7308,6810,2591,713,279.0
19,2021,08,3424.0,5541.0,12236,8925,8353,8237,4364,1364,629.0
20,2021,09,3874.0,5964.0,13556,11266,10157,7223,4982,1923,906.0
21,2021,10,4207.0,6855.0,8963,9008,7936,5822,6117,2748,1751.0
22,2021,11,7214.0,9525.0,7450,10213,9726,10338,15516,7760,4757.0
23,2021,12,20783.0,19474.0,18184,23245,24414,24350,33198,13582,6285.0
24,2022,01,25542.0,35769.0,43080,32855,33524,22340,13272,4742,3556.0
25,2022,02,297636.0,329742.0,394189,348856,369683,257524,175967,68443,45806.0
26,2022,03,1279285.0,1352696.0,1390640,1463168,1533008,1201246,997873,461844,279610.0
27,2022,04,448522.0,481777.0,554366,601973,639868,546779,468720,248930,151160.0
28,2022,05,74973.0,108245.0,147723,122847,126999,114821,91553,49269,29484.0
29,2022,06,20629.0,32193.0,55015,39343,37247,32572,22896,10240,5445.0
30,2022,07,125286.0,200684.0,260737,215638,214643,181020,126705,60949,30301.0
31,2022,08,295667.0,372182.0,526134,496001,510309,495779,417446,229642,126727.0
32,2022,09,130031.0,192161.0,195593,203492,223579,207778,191533,112508,66046.0
33,2022,10,54166.0,94171.0,100544,109425,116301,111750,103100,61356,37608.0
34,2022,11,97997.0,174410.0,205416,219729,230072,221634,198906,115754,77400.0
35,2022,12,117836.0,229013.0,268421,296395,301837,287658,242678,129443,87298.0
36,2023,01,59399.0,96262.0,158588,171902,171203,167410,148364,85888,58347.0
37,2023,02,20601.0,28367.0,47981,52832,50101,46981,43966,26998,19470.0
38,2023,03,17760.0,45567.0,46316,45220,43444,38520,34463,21085,14627.0
39,2023,04,15503.0,36702.0,51065,56736,51145,46930,46767,29067,19148.0
40,2023,05,21431.0,61744.0,77476,83275,75658,68542,71734,44984,28503.0
41,2023,06,22743.0,59677.0,67360,78237,72981,67012,72696,43725,24345.0
42,2023,07,39774.0,122479.0,131080,145442,145700,132112,137775,86238,49027.0
43,2023,08,56328.0,130034.0,184949,202606,198037,190991,202496,126479,78436.0

In [14]:
df2.to_csv('df_confirmed_case_covid_202001_202308_10age.csv')

In [15]:
# df_population1= pd.read_csv('202303_202308_연령별인구현황_월간.csv', encoding = 'euc-kr')
# df_population_total = df_population.iloc[0].to_frame()
# df_population_total.to_csv('test1')

In [16]:
df_population1= pd.read_csv('202001_202002_연령별인구현황_월간.csv', encoding = 'euc-kr', thousands = ',')
df_population2= pd.read_csv('202003_202008_연령별인구현황_월간.csv', encoding = 'euc-kr', thousands = ',')
df_population3= pd.read_csv('202009_202102_연령별인구현황_월간.csv', encoding = 'euc-kr', thousands = ',')
df_population4= pd.read_csv('202103_202108_연령별인구현황_월간.csv', encoding = 'euc-kr', thousands = ',')
df_population5= pd.read_csv('202109_202202_연령별인구현황_월간.csv', encoding = 'euc-kr', thousands = ',')
df_population6= pd.read_csv('202203_202208_연령별인구현황_월간.csv', encoding = 'euc-kr', thousands = ',')
df_population7= pd.read_csv('202209_202302_연령별인구현황_월간.csv', encoding = 'euc-kr', thousands = ',')
df_population8= pd.read_csv('202303_202308_연령별인구현황_월간.csv', encoding = 'euc-kr', thousands = ',')

concat_list = [df_population1, df_population2, df_population3, df_population4, df_population5, df_population6, df_population7, df_population8]
df_population = pd.concat(concat_list)

In [17]:
df_population_total = df_population.loc[df_population['행정구역'] == '전국  (0000000000)']
df_population_total
df_population_total = df_population_total.replace(np.nan,0)

In [18]:
# df_final = pd.DataFrame(columns = ['year', 'month', '계(명)', '0-9세', '10-19세', '20-29세', '30-39세', '40-49세','50-59세', '60-69세', '70-79세', '80세이상'])
#df_final

In [19]:
df_population_total = df_population_total.T

In [20]:
df_population_total = df_population_total.iloc[1:,:]
df_population_total

                             0    0    0    0    0    0    0          0
2020년01월_계_총인구수     51847509.0  0.0  0.0  0.0  0.0  0.0  0.0        0.0
2020년01월_계_연령구간인구수  51847509.0  0.0  0.0  0.0  0.0  0.0  0.0        0.0
2020년01월_계_0~9세      4148654.0  0.0  0.0  0.0  0.0  0.0  0.0        0.0
2020년01월_계_10~19세    4940455.0  0.0  0.0  0.0  0.0  0.0  0.0        0.0
2020년01월_계_20~29세    6806410.0  0.0  0.0  0.0  0.0  0.0  0.0        0.0
...                        ...  ...  ...  ...  ...  ...  ...        ...
2023년08월_계_60~69세          0.0  0.0  0.0  0.0  0.0  0.0  0.0  7589676.0
2023년08월_계_70~79세          0.0  0.0  0.0  0.0  0.0  0.0  0.0  3918796.0
2023년08월_계_80~89세          0.0  0.0  0.0  0.0  0.0  0.0  0.0  2030118.0
2023년08월_계_90~99세          0.0  0.0  0.0  0.0  0.0  0.0  0.0   292625.0
2023년08월_계_100세 이상         0.0  0.0  0.0  0.0  0.0  0.0  0.0     8929.0

[572 rows x 8 columns]

In [21]:
year = df_population_total.index.astype('str').str.slice(0,4)
year 
df_population_total['year'] = year
df_population_total

                             0    0    0    0    0    0    0          0  year
2020년01월_계_총인구수     51847509.0  0.0  0.0  0.0  0.0  0.0  0.0        0.0  2020
2020년01월_계_연령구간인구수  51847509.0  0.0  0.0  0.0  0.0  0.0  0.0        0.0  2020
2020년01월_계_0~9세      4148654.0  0.0  0.0  0.0  0.0  0.0  0.0        0.0  2020
2020년01월_계_10~19세    4940455.0  0.0  0.0  0.0  0.0  0.0  0.0        0.0  2020
2020년01월_계_20~29세    6806410.0  0.0  0.0  0.0  0.0  0.0  0.0        0.0  2020
...                        ...  ...  ...  ...  ...  ...  ...        ...   ...
2023년08월_계_60~69세          0.0  0.0  0.0  0.0  0.0  0.0  0.0  7589676.0  2023
2023년08월_계_70~79세          0.0  0.0  0.0  0.0  0.0  0.0  0.0  3918796.0  2023
2023년08월_계_80~89세          0.0  0.0  0.0  0.0  0.0  0.0  0.0  2030118.0  2023
2023년08월_계_90~99세          0.0  0.0  0.0  0.0  0.0  0.0  0.0   292625.0  2023
2023년08월_계_100세 이상         0.0  0.0  0.0  0.0  0.0  0.0  0.0     8929.0  2023

[572 rows x 9 columns]

In [22]:
month = df_population_total.index.astype('str').str.slice(5,7)
month
df_population_total['month'] = month
df_population_total

,0,0,0,0,0,0,0,0,year,month
2020년01월_계_총인구수,51847509.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2020,01
2020년01월_계_연령구간인구수,51847509.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2020,01
2020년01월_계_0~9세,4148654.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2020,01
2020년01월_계_10~19세,4940455.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2020,01
2020년01월_계_20~29세,6806410.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2020,01
...,...,...,...,...,...,...,...,...,...,...
2023년08월_계_60~69세,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7589676.0,2023,08
2023년08월_계_70~79세,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3918796.0,2023,08
2023년08월_계_80~89세,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2030118.0,2023,08
2023년08월_계_90~99세,0.0,0.0,0.0,0.0,0.0,0.0,0.0,292625.0,2023,08
2023년08월_계_100세 이상,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8929.0,2023,08

In [23]:
con = df_population_total.index.astype('str').str[9:]
con
df_population_total['con'] = con
df_population_total

,0,0,0,0,0,0,0,0,year,month,con
2020년01월_계_총인구수,51847509.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2020,01,계_총인구수
2020년01월_계_연령구간인구수,51847509.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2020,01,계_연령구간인구수
2020년01월_계_0~9세,4148654.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2020,01,계_0~9세
2020년01월_계_10~19세,4940455.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2020,01,계_10~19세
2020년01월_계_20~29세,6806410.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2020,01,계_20~29세
...,...,...,...,...,...,...,...,...,...,...,...
2023년08월_계_60~69세,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7589676.0,2023,08,계_60~69세
2023년08월_계_70~79세,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3918796.0,2023,08,계_70~79세
2023년08월_계_80~89세,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2030118.0,2023,08,계_80~89세
2023년08월_계_90~99세,0.0,0.0,0.0,0.0,0.0,0.0,0.0,292625.0,2023,08,계_90~99세
2023년08월_계_100세 이상,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8929.0,2023,08,계_100세 이상

In [24]:
df_population_total.info()

<class 'pandas.core.frame.DataFrame'>
Index: 572 entries, 2020년01월_계_총인구수 to 2023년08월_계_100세 이상
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       572 non-null    object
 1   0       572 non-null    object
 2   0       572 non-null    object
 3   0       572 non-null    object
 4   0       572 non-null    object
 5   0       572 non-null    object
 6   0       572 non-null    object
 7   0       572 non-null    object
 8   year    572 non-null    object
 9   month   572 non-null    object
 10  con     572 non-null    object
dtypes: object(11)
memory usage: 53.6+ KB

In [25]:
total = df_population_total.iloc[:,:8].astype(int).sum(axis =1)
total
df_population_total['계(명)'] = total.astype(int)
df_population_total

,0,0,0,0,0,0,0,0,year,month,con,계(명)
2020년01월_계_총인구수,51847509.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2020,01,계_총인구수,51847509
2020년01월_계_연령구간인구수,51847509.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2020,01,계_연령구간인구수,51847509
2020년01월_계_0~9세,4148654.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2020,01,계_0~9세,4148654
2020년01월_계_10~19세,4940455.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2020,01,계_10~19세,4940455
2020년01월_계_20~29세,6806410.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2020,01,계_20~29세,6806410
...,...,...,...,...,...,...,...,...,...,...,...,...
2023년08월_계_60~69세,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7589676.0,2023,08,계_60~69세,7589676
2023년08월_계_70~79세,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3918796.0,2023,08,계_70~79세,3918796
2023년08월_계_80~89세,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2030118.0,2023,08,계_80~89세,2030118
2023년08월_계_90~99세,0.0,0.0,0.0,0.0,0.0,0.0,0.0,292625.0,2023,08,계_90~99세,292625
2023년08월_계_100세 이상,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8929.0,2023,08,계_100세 이상,8929

In [26]:
# df_population_total_1  = df_population_total.loc[df_population_total['con'] == '계_총인구수']
# df_population_total_1

In [27]:
# df_population_total_2  = df_population_total.loc[df_population_total['con'] == '계_0~9세']
# df_population_total_2

In [28]:
df = df_population_total.copy()

In [29]:
df.head()

,0,0,0,0,0,0,0,0,year,month,con,계(명)
2020년01월_계_총인구수,51847509.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2020,01,계_총인구수,51847509
2020년01월_계_연령구간인구수,51847509.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2020,01,계_연령구간인구수,51847509
2020년01월_계_0~9세,4148654.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2020,01,계_0~9세,4148654
2020년01월_계_10~19세,4940455.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2020,01,계_10~19세,4940455
2020년01월_계_20~29세,6806410.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2020,01,계_20~29세,6806410

In [30]:
df = df.iloc[:, 8:]
df

                    year month        con      계(명)
2020년01월_계_총인구수     2020    01     계_총인구수  51847509
2020년01월_계_연령구간인구수  2020    01  계_연령구간인구수  51847509
2020년01월_계_0~9세     2020    01     계_0~9세   4148654
2020년01월_계_10~19세   2020    01   계_10~19세   4940455
2020년01월_계_20~29세   2020    01   계_20~29세   6806410
...                  ...   ...        ...       ...
2023년08월_계_60~69세   2023    08   계_60~69세   7589676
2023년08월_계_70~79세   2023    08   계_70~79세   3918796
2023년08월_계_80~89세   2023    08   계_80~89세   2030118
2023년08월_계_90~99세   2023    08   계_90~99세    292625
2023년08월_계_100세 이상  2023    08  계_100세 이상      8929

[572 rows x 4 columns]

In [31]:
df_population_total = df.pivot(index=['year','month'],columns=['con'],values=['계(명)'])
df_population_total.head()

               계(명)                                                         \
con          계_0~9세 계_100세 이상 계_10~19세 계_20~29세 계_30~39세 계_40~49세 계_50~59세
year month
2020 01     4148654     20381  4940455  6806410  7045120  8389281  8666971
     02     4134824     20591  4920794  6786097  7026850  8397417  8666798
     03     4119475     20758  4902009  6799238  7006749  8375429  8662400
     04     4103848     20913  4887408  6802925  6995799  8362127  8661935
     05     4089462     21060  4872081  6804350  6985248  8346911  8668601


con        계_60~69세 계_70~79세 계_80~89세 계_90~99세 계_연령구간인구수    계_총인구수
year month
2020 01     6344284  3607104  1644448   234401  51847509  51847509
     02     6385073  3612980  1656304   236899  51844627  51844627
     03     6426006  3623899  1667665   239567  51843195  51843195
     04     6456674  3632966  1676737   241192  51842524  51842524
     05     6481317  3646121  1683807   242413  51841371  51841371

In [32]:
df_population_total.columns

MultiIndex([('계(명)',    '계_0~9세'),
            ('계(명)', '계_100세 이상'),
            ('계(명)',  '계_10~19세'),
            ('계(명)',  '계_20~29세'),
            ('계(명)',  '계_30~39세'),
            ('계(명)',  '계_40~49세'),
            ('계(명)',  '계_50~59세'),
            ('계(명)',  '계_60~69세'),
            ('계(명)',  '계_70~79세'),
            ('계(명)',  '계_80~89세'),
            ('계(명)',  '계_90~99세'),
            ('계(명)', '계_연령구간인구수'),
            ('계(명)',    '계_총인구수')],
           names=[None, 'con'])

In [33]:
df_population_total =df_population_total.reset_index()
df_population_total.head()

     year month     계(명)                                                \
con               계_0~9세 계_100세 이상 계_10~19세 계_20~29세 계_30~39세 계_40~49세
0    2020    01  4148654     20381  4940455  6806410  7045120  8389281
1    2020    02  4134824     20591  4920794  6786097  7026850  8397417
2    2020    03  4119475     20758  4902009  6799238  7006749  8375429
3    2020    04  4103848     20913  4887408  6802925  6995799  8362127
4    2020    05  4089462     21060  4872081  6804350  6985248  8346911


con 계_50~59세 계_60~69세 계_70~79세 계_80~89세 계_90~99세 계_연령구간인구수    계_총인구수
0    8666971  6344284  3607104  1644448   234401  51847509  51847509
1    8666798  6385073  3612980  1656304   236899  51844627  51844627
2    8662400  6426006  3623899  1667665   239567  51843195  51843195
3    8661935  6456674  3632966  1676737   241192  51842524  51842524
4    8668601  6481317  3646121  1683807   242413  51841371  51841371

In [34]:
df_population_total.columns

MultiIndex([( 'year',          ''),
            ('month',          ''),
            ( '계(명)',    '계_0~9세'),
            ( '계(명)', '계_100세 이상'),
            ( '계(명)',  '계_10~19세'),
            ( '계(명)',  '계_20~29세'),
            ( '계(명)',  '계_30~39세'),
            ( '계(명)',  '계_40~49세'),
            ( '계(명)',  '계_50~59세'),
            ( '계(명)',  '계_60~69세'),
            ( '계(명)',  '계_70~79세'),
            ( '계(명)',  '계_80~89세'),
            ( '계(명)',  '계_90~99세'),
            ( '계(명)', '계_연령구간인구수'),
            ( '계(명)',    '계_총인구수')],
           names=[None, 'con'])

In [35]:
df_population_total.columns = df_population_total.columns.droplevel(0)
df_population_total.head()

con,,,계_0~9세,계_100세 이상,계_10~19세,계_20~29세,계_30~39세,계_40~49세,계_50~59세,계_60~69세,계_70~79세,계_80~89세,계_90~99세,계_연령구간인구수,계_총인구수
0,2020,01,4148654,20381,4940455,6806410,7045120,8389281,8666971,6344284,3607104,1644448,234401,51847509,51847509
1,2020,02,4134824,20591,4920794,6786097,7026850,8397417,8666798,6385073,3612980,1656304,236899,51844627,51844627
2,2020,03,4119475,20758,4902009,6799238,7006749,8375429,8662400,6426006,3623899,1667665,239567,51843195,51843195
3,2020,04,4103848,20913,4887408,6802925,6995799,8362127,8661935,6456674,3632966,1676737,241192,51842524,51842524
4,2020,05,4089462,21060,4872081,6804350,6985248,8346911,8668601,6481317,3646121,1683807,242413,51841371,51841371

In [36]:
df_population_total.columns

Index(['', '', '계_0~9세', '계_100세 이상', '계_10~19세', '계_20~29세', '계_30~39세',
       '계_40~49세', '계_50~59세', '계_60~69세', '계_70~79세', '계_80~89세', '계_90~99세',
       '계_연령구간인구수', '계_총인구수'],
      dtype='object', name='con')

In [37]:
df_population_total = df_population_total.iloc[:,0:13]
df_population_total.head()

con,,,계_0~9세,계_100세 이상,계_10~19세,계_20~29세,계_30~39세,계_40~49세,계_50~59세,계_60~69세,계_70~79세,계_80~89세,계_90~99세
0,2020,01,4148654,20381,4940455,6806410,7045120,8389281,8666971,6344284,3607104,1644448,234401
1,2020,02,4134824,20591,4920794,6786097,7026850,8397417,8666798,6385073,3612980,1656304,236899
2,2020,03,4119475,20758,4902009,6799238,7006749,8375429,8662400,6426006,3623899,1667665,239567
3,2020,04,4103848,20913,4887408,6802925,6995799,8362127,8661935,6456674,3632966,1676737,241192
4,2020,05,4089462,21060,4872081,6804350,6985248,8346911,8668601,6481317,3646121,1683807,242413

In [38]:
df_population_total.columns =  np.concatenate([np.array(['year','month']),df_population_total.columns[2:]])

In [39]:
df_population_total.head()

,year,month,계_0~9세,계_100세 이상,계_10~19세,계_20~29세,계_30~39세,계_40~49세,계_50~59세,계_60~69세,계_70~79세,계_80~89세,계_90~99세
0,2020,01,4148654,20381,4940455,6806410,7045120,8389281,8666971,6344284,3607104,1644448,234401
1,2020,02,4134824,20591,4920794,6786097,7026850,8397417,8666798,6385073,3612980,1656304,236899
2,2020,03,4119475,20758,4902009,6799238,7006749,8375429,8662400,6426006,3623899,1667665,239567
3,2020,04,4103848,20913,4887408,6802925,6995799,8362127,8661935,6456674,3632966,1676737,241192
4,2020,05,4089462,21060,4872081,6804350,6985248,8346911,8668601,6481317,3646121,1683807,242413

In [40]:
df_population_total['80세이상'] = df_population_total.iloc[:,[3,11,12]].sum(1)

In [41]:
df_population_total.drop(columns=df_population_total.iloc[:,[3,11,12]].columns,inplace=True)

In [42]:
df_population_total.head()

,year,month,계_0~9세,계_10~19세,계_20~29세,계_30~39세,계_40~49세,계_50~59세,계_60~69세,계_70~79세,80세이상
0,2020,01,4148654,4940455,6806410,7045120,8389281,8666971,6344284,3607104,1899230
1,2020,02,4134824,4920794,6786097,7026850,8397417,8666798,6385073,3612980,1913794
2,2020,03,4119475,4902009,6799238,7006749,8375429,8662400,6426006,3623899,1927990
3,2020,04,4103848,4887408,6802925,6995799,8362127,8661935,6456674,3632966,1938842
4,2020,05,4089462,4872081,6804350,6985248,8346911,8668601,6481317,3646121,1947280

In [43]:
df_population_total['계(명)'] = df_population_total.iloc[:,2:].sum(1)
df_population_total.head()

,year,month,계_0~9세,계_10~19세,계_20~29세,계_30~39세,계_40~49세,계_50~59세,계_60~69세,계_70~79세,80세이상,계(명)
0,2020,01,4148654,4940455,6806410,7045120,8389281,8666971,6344284,3607104,1899230,51847509
1,2020,02,4134824,4920794,6786097,7026850,8397417,8666798,6385073,3612980,1913794,51844627
2,2020,03,4119475,4902009,6799238,7006749,8375429,8662400,6426006,3623899,1927990,51843195
3,2020,04,4103848,4887408,6802925,6995799,8362127,8661935,6456674,3632966,1938842,51842524
4,2020,05,4089462,4872081,6804350,6985248,8346911,8668601,6481317,3646121,1947280,51841371

In [44]:
df_population_total.columns = ['year','month', '0-9(population)', '10-19(population)', '20-29(population)',
       '30-39(population)', '40-49(population)', '50-59(population)',
       '60-69(population)', '70-79(population)', 'over80(population)', '계(명)']

In [45]:
df_population_total=df_population_total[['year', 'month', '0-9(population)', '10-19(population)', '20-29(population)',
       '30-39(population)', '40-49(population)', '50-59(population)',
       '60-69(population)', '70-79(population)', 'over80(population)']]

In [46]:
df_population_total

,year,month,0-9(population),10-19(population),20-29(population),30-39(population),40-49(population),50-59(population),60-69(population),70-79(population),over80(population)
0,2020,01,4148654,4940455,6806410,7045120,8389281,8666971,6344284,3607104,1899230
1,2020,02,4134824,4920794,6786097,7026850,8397417,8666798,6385073,3612980,1913794
2,2020,03,4119475,4902009,6799238,7006749,8375429,8662400,6426006,3623899,1927990
3,2020,04,4103848,4887408,6802925,6995799,8362127,8661935,6456674,3632966,1938842
4,2020,05,4089462,4872081,6804350,6985248,8346911,8668601,6481317,3646121,1947280
5,2020,06,4075794,4861506,6803579,6972185,8342267,8652260,6523322,3658049,1950446
6,2020,07,4062274,4850566,6801367,6956361,8338271,8653176,6549914,3671175,1956748
7,2020,08,4045950,4838700,6800612,6939804,8330276,8651547,6590179,3676849,1966036
8,2020,09,4027765,4828702,6801056,6922566,8321409,8652305,6630461,3680759,1976763
9,2020,10,4005030,4818481,6802784,6900752,8312221,8655292,6669780,3687451,1986225
10,2020,11,3984472,4807963,6804936,6884029,8305172,8653322,6707084,3693926,1993398
11,2020,12,3970070,4793336,6806153,6873117,8294787,8645014,6744506,3698246,2003794
12,2021,01,3944244,4784388,6792483,6856414,8285935,8642700,6794549,3707683,2017536
13,2021,02,3927428,4772917,6771959,6834586,8287143,8644918,6840597,3710261,2034333
14,2021,03,3908794,4761113,6767952,6812701,8250451,8613059,6876287,3694544,2021004
15,2021,04,3891405,4753626,6761949,6802386,8244087,8604370,6918145,3693918,2032214
16,2021,05,3874174,4746103,6754283,6788072,8220344,8606589,6957802,3694633,2041025
17,2021,06,3859229,4741570,6745313,6775108,8216263,8590314,7001815,3694311,2048477
18,2021,07,3843759,4737829,6733054,6764334,8205797,8591085,7039371,3699044,2057296
19,2021,08,3827185,4733729,6721376,6753189,8192793,8598568,7072000,3703046,2067830
20,2021,09,3809849,4727626,6708734,6745531,8182067,8610979,7097818,3705737,2079347
21,2021,10,3792548,4721726,6691903,6739933,8169827,8622455,7124259,3710920,2088719
22,2021,11,3775503,4716775,6674970,6731509,8165990,8631102,7147578,3712470,2096807
23,2021,12,3760350,4709316,6655923,6723435,8166792,8635211,7164712,3715084,2107986
24,2022,01,3736642,4706002,6632711,6704271,8166823,8635055,7196303,3724894,2129772
25,2022,02,3718850,4702667,6606751,6681507,8172801,8630063,7228356,3736880,2147686
26,2022,03,3697734,4699914,6594325,6673424,8157546,8638696,7237134,3749844,2162078
27,2022,04,3679892,4697255,6579507,6666711,8153849,8647758,7243664,3755435,2168589
28,2022,05,3662692,4695186,6564754,6660669,8142338,8650247,7245254,3783011,2179571
29,2022,06,3644574,4696377,6547881,6653299,8141674,8649731,7260782,3795157,2188703
30,2022,07,3624681,4696767,6531636,6647003,8134712,8651892,7279621,3807864,2200270
31,2022,08,3606212,4698846,6513110,6640555,8122023,8645832,7303567,3815045,2213251
32,2022,09,3587171,4700253,6487234,6629383,8099849,8623902,7309977,3813420,2215469
33,2022,10,3566622,4703349,6463741,6625319,8088855,8614576,7346707,3814072,2236385
34,2022,11,3548291,4704693,6441542,6620713,8083707,8607789,7379420,3818887,2245787
35,2022,12,3532642,4703196,6417181,6615511,8073117,8612064,7403539,3825717,2256071
36,2023,01,3510756,4702482,6393461,6600252,8065721,8616924,7434333,3835199,2270890
37,2023,02,3494655,4697666,6366296,6581804,8068794,8622349,7461127,3840239,2288549
38,2023,03,3478290,4690388,6349354,6585469,8047460,8620204,7485540,3855550,2302026
39,2023,04,3460142,4684275,6333731,6589037,8027947,8609976,7525051,3865977,2312019
40,2023,05,3445285,4679181,6318641,6588734,8007347,8622447,7537569,3883027,2318290
41,2023,06,3431910,4676000,6301901,6588552,7998075,8627184,7553882,3894490,2320751
42,2023,07,3415119,4674885,6284235,6588036,7988791,8631299,7571631,3907575,2325562
43,2023,08,3398415,4673674,6265976,6587136,7977613,8634255,7589676,3918796,2331672

In [47]:
df_population_total.to_csv('df_population_202001_202308_10age.csv')

In [48]:
df_population = pd.read_csv('df_population_202001_202308_10age.csv')
df_confirmed = pd.read_csv('df_confirmed_case_covid_202001_202308_10age.csv')

In [49]:
df_confirmed

,Unnamed: 0,year,month,0-9(confirmed_case),10-19(confirmed_case),20-29(confirmed_case),30-39(confirmed_case),40-49(confirmed_case),50-59(confirmed_case),60-69(confirmed_case),70-79(confirmed_case),over80(confirmed_case)
0,0,2020,1,0.0,0.0,3,2,0,5,1,0,0.0
1,1,2020,2,19.0,99.0,853,358,437,578,389,133,54.0
2,2,2020,3,94.0,416.0,1798,653,878,1266,845,518,387.0
3,3,2020,4,27.0,76.0,297,145,112,107,113,58,44.0
4,4,2020,5,17.0,66.0,223,134,94,83,57,16,13.0
5,5,2020,6,35.0,51.0,188,204,160,247,263,125,58.0
6,6,2020,7,54.0,74.0,258,314,249,233,185,97,42.0
7,7,2020,8,196.0,363.0,700,681,763,1119,1114,517,188.0
8,8,2020,9,136.0,161.0,442,417,485,783,814,442,185.0
9,9,2020,10,114.0,151.0,407,376,385,451,427,210,179.0
10,10,2020,11,301.0,592.0,1296,1096,1233,1347,1031,507,285.0
11,11,2020,12,1098.0,1720.0,3243,3346,3825,5174,4385,2145,1587.0
12,12,2021,1,893.0,1433.0,2235,2246,2591,3282,2644,1242,904.0
13,13,2021,2,637.0,829.0,1597,1732,1643,2021,1756,801,450.0
14,14,2021,3,749.0,978.0,1922,2131,2151,2318,1964,825,376.0
15,15,2021,4,913.0,1520.0,2735,2596,3061,3554,2791,1186,571.0
16,16,2021,5,910.0,1469.0,2884,2837,3070,3253,2515,985,406.0
17,17,2021,6,959.0,1346.0,3062,2780,3087,2938,1771,515,165.0
18,18,2021,7,2479.0,4335.0,9890,6967,7308,6810,2591,713,279.0
19,19,2021,8,3424.0,5541.0,12236,8925,8353,8237,4364,1364,629.0
20,20,2021,9,3874.0,5964.0,13556,11266,10157,7223,4982,1923,906.0
21,21,2021,10,4207.0,6855.0,8963,9008,7936,5822,6117,2748,1751.0
22,22,2021,11,7214.0,9525.0,7450,10213,9726,10338,15516,7760,4757.0
23,23,2021,12,20783.0,19474.0,18184,23245,24414,24350,33198,13582,6285.0
24,24,2022,1,25542.0,35769.0,43080,32855,33524,22340,13272,4742,3556.0
25,25,2022,2,297636.0,329742.0,394189,348856,369683,257524,175967,68443,45806.0
26,26,2022,3,1279285.0,1352696.0,1390640,1463168,1533008,1201246,997873,461844,279610.0
27,27,2022,4,448522.0,481777.0,554366,601973,639868,546779,468720,248930,151160.0
28,28,2022,5,74973.0,108245.0,147723,122847,126999,114821,91553,49269,29484.0
29,29,2022,6,20629.0,32193.0,55015,39343,37247,32572,22896,10240,5445.0
30,30,2022,7,125286.0,200684.0,260737,215638,214643,181020,126705,60949,30301.0
31,31,2022,8,295667.0,372182.0,526134,496001,510309,495779,417446,229642,126727.0
32,32,2022,9,130031.0,192161.0,195593,203492,223579,207778,191533,112508,66046.0
33,33,2022,10,54166.0,94171.0,100544,109425,116301,111750,103100,61356,37608.0
34,34,2022,11,97997.0,174410.0,205416,219729,230072,221634,198906,115754,77400.0
35,35,2022,12,117836.0,229013.0,268421,296395,301837,287658,242678,129443,87298.0
36,36,2023,1,59399.0,96262.0,158588,171902,171203,167410,148364,85888,58347.0
37,37,2023,2,20601.0,28367.0,47981,52832,50101,46981,43966,26998,19470.0
38,38,2023,3,17760.0,45567.0,46316,45220,43444,38520,34463,21085,14627.0
39,39,2023,4,15503.0,36702.0,51065,56736,51145,46930,46767,29067,19148.0
40,40,2023,5,21431.0,61744.0,77476,83275,75658,68542,71734,44984,28503.0
41,41,2023,6,22743.0,59677.0,67360,78237,72981,67012,72696,43725,24345.0
42,42,2023,7,39774.0,122479.0,131080,145442,145700,132112,137775,86238,49027.0
43,43,2023,8,56328.0,130034.0,184949,202606,198037,190991,202496,126479,78436.0

In [50]:
df_rate = pd.DataFrame(df_confirmed.values/df_population.values,columns=df_population.columns)
df_rate.head()

,Unnamed: 0,year,month,0-9(population),10-19(population),20-29(population),30-39(population),40-49(population),50-59(population),60-69(population),70-79(population),over80(population)
0,NaN,1.0,1.0,0.000000,0.000000,4.407610e-07,2.838844e-07,0.000000,5.769028e-07,1.576222e-07,0.000000,0.000000
1,1.0,1.0,1.0,0.000005,0.000020,1.256982e-04,5.094744e-05,0.000052,6.669130e-05,6.092334e-05,0.000037,0.000028
2,1.0,1.0,1.0,0.000023,0.000085,2.644414e-04,9.319586e-05,0.000105,1.461489e-04,1.314969e-04,0.000143,0.000201
3,1.0,1.0,1.0,0.000007,0.000016,4.365769e-05,2.072672e-05,0.000013,1.235290e-05,1.750127e-05,0.000016,0.000023
4,1.0,1.0,1.0,0.000004,0.000014,3.277315e-05,1.918328e-05,0.000011,9.574786e-06,8.794509e-06,0.000004,0.000007

In [51]:
df_rate = df_rate.iloc[:, 3:]

In [52]:
df_rate.columns

Index(['0-9(population)', '10-19(population)', '20-29(population)',
       '30-39(population)', '40-49(population)', '50-59(population)',
       '60-69(population)', '70-79(population)', 'over80(population)'],
      dtype='object')

In [53]:
df_rate.columns = ['0-9(rate)', '10-19(rate)', '20-29(rate)',
       '30-39(rate)', '40-49(rate)',
       '50-59(rate)', '60-69(rate)',
       '70-79(rate)', 'over80(rate)']

In [54]:
df_rate.head()

,0-9(rate),10-19(rate),20-29(rate),30-39(rate),40-49(rate),50-59(rate),60-69(rate),70-79(rate),over80(rate)
0,0.000000,0.000000,4.407610e-07,2.838844e-07,0.000000,5.769028e-07,1.576222e-07,0.000000,0.000000
1,0.000005,0.000020,1.256982e-04,5.094744e-05,0.000052,6.669130e-05,6.092334e-05,0.000037,0.000028
2,0.000023,0.000085,2.644414e-04,9.319586e-05,0.000105,1.461489e-04,1.314969e-04,0.000143,0.000201
3,0.000007,0.000016,4.365769e-05,2.072672e-05,0.000013,1.235290e-05,1.750127e-05,0.000016,0.000023
4,0.000004,0.000014,3.277315e-05,1.918328e-05,0.000011,9.574786e-06,8.794509e-06,0.000004,0.000007

In [55]:
df_confirmed

,Unnamed: 0,year,month,0-9(confirmed_case),10-19(confirmed_case),20-29(confirmed_case),30-39(confirmed_case),40-49(confirmed_case),50-59(confirmed_case),60-69(confirmed_case),70-79(confirmed_case),over80(confirmed_case)
0,0,2020,1,0.0,0.0,3,2,0,5,1,0,0.0
1,1,2020,2,19.0,99.0,853,358,437,578,389,133,54.0
2,2,2020,3,94.0,416.0,1798,653,878,1266,845,518,387.0
3,3,2020,4,27.0,76.0,297,145,112,107,113,58,44.0
4,4,2020,5,17.0,66.0,223,134,94,83,57,16,13.0
5,5,2020,6,35.0,51.0,188,204,160,247,263,125,58.0
6,6,2020,7,54.0,74.0,258,314,249,233,185,97,42.0
7,7,2020,8,196.0,363.0,700,681,763,1119,1114,517,188.0
8,8,2020,9,136.0,161.0,442,417,485,783,814,442,185.0
9,9,2020,10,114.0,151.0,407,376,385,451,427,210,179.0
10,10,2020,11,301.0,592.0,1296,1096,1233,1347,1031,507,285.0
11,11,2020,12,1098.0,1720.0,3243,3346,3825,5174,4385,2145,1587.0
12,12,2021,1,893.0,1433.0,2235,2246,2591,3282,2644,1242,904.0
13,13,2021,2,637.0,829.0,1597,1732,1643,2021,1756,801,450.0
14,14,2021,3,749.0,978.0,1922,2131,2151,2318,1964,825,376.0
15,15,2021,4,913.0,1520.0,2735,2596,3061,3554,2791,1186,571.0
16,16,2021,5,910.0,1469.0,2884,2837,3070,3253,2515,985,406.0
17,17,2021,6,959.0,1346.0,3062,2780,3087,2938,1771,515,165.0
18,18,2021,7,2479.0,4335.0,9890,6967,7308,6810,2591,713,279.0
19,19,2021,8,3424.0,5541.0,12236,8925,8353,8237,4364,1364,629.0
20,20,2021,9,3874.0,5964.0,13556,11266,10157,7223,4982,1923,906.0
21,21,2021,10,4207.0,6855.0,8963,9008,7936,5822,6117,2748,1751.0
22,22,2021,11,7214.0,9525.0,7450,10213,9726,10338,15516,7760,4757.0
23,23,2021,12,20783.0,19474.0,18184,23245,24414,24350,33198,13582,6285.0
24,24,2022,1,25542.0,35769.0,43080,32855,33524,22340,13272,4742,3556.0
25,25,2022,2,297636.0,329742.0,394189,348856,369683,257524,175967,68443,45806.0
26,26,2022,3,1279285.0,1352696.0,1390640,1463168,1533008,1201246,997873,461844,279610.0
27,27,2022,4,448522.0,481777.0,554366,601973,639868,546779,468720,248930,151160.0
28,28,2022,5,74973.0,108245.0,147723,122847,126999,114821,91553,49269,29484.0
29,29,2022,6,20629.0,32193.0,55015,39343,37247,32572,22896,10240,5445.0
30,30,2022,7,125286.0,200684.0,260737,215638,214643,181020,126705,60949,30301.0
31,31,2022,8,295667.0,372182.0,526134,496001,510309,495779,417446,229642,126727.0
32,32,2022,9,130031.0,192161.0,195593,203492,223579,207778,191533,112508,66046.0
33,33,2022,10,54166.0,94171.0,100544,109425,116301,111750,103100,61356,37608.0
34,34,2022,11,97997.0,174410.0,205416,219729,230072,221634,198906,115754,77400.0
35,35,2022,12,117836.0,229013.0,268421,296395,301837,287658,242678,129443,87298.0
36,36,2023,1,59399.0,96262.0,158588,171902,171203,167410,148364,85888,58347.0
37,37,2023,2,20601.0,28367.0,47981,52832,50101,46981,43966,26998,19470.0
38,38,2023,3,17760.0,45567.0,46316,45220,43444,38520,34463,21085,14627.0
39,39,2023,4,15503.0,36702.0,51065,56736,51145,46930,46767,29067,19148.0
40,40,2023,5,21431.0,61744.0,77476,83275,75658,68542,71734,44984,28503.0
41,41,2023,6,22743.0,59677.0,67360,78237,72981,67012,72696,43725,24345.0
42,42,2023,7,39774.0,122479.0,131080,145442,145700,132112,137775,86238,49027.0
43,43,2023,8,56328.0,130034.0,184949,202606,198037,190991,202496,126479,78436.0

In [56]:
df_confirmed = df_confirmed.iloc[:, 3:]
df_confirmed

,0-9(confirmed_case),10-19(confirmed_case),20-29(confirmed_case),30-39(confirmed_case),40-49(confirmed_case),50-59(confirmed_case),60-69(confirmed_case),70-79(confirmed_case),over80(confirmed_case)
0,0.0,0.0,3,2,0,5,1,0,0.0
1,19.0,99.0,853,358,437,578,389,133,54.0
2,94.0,416.0,1798,653,878,1266,845,518,387.0
3,27.0,76.0,297,145,112,107,113,58,44.0
4,17.0,66.0,223,134,94,83,57,16,13.0
5,35.0,51.0,188,204,160,247,263,125,58.0
6,54.0,74.0,258,314,249,233,185,97,42.0
7,196.0,363.0,700,681,763,1119,1114,517,188.0
8,136.0,161.0,442,417,485,783,814,442,185.0
9,114.0,151.0,407,376,385,451,427,210,179.0
10,301.0,592.0,1296,1096,1233,1347,1031,507,285.0
11,1098.0,1720.0,3243,3346,3825,5174,4385,2145,1587.0
12,893.0,1433.0,2235,2246,2591,3282,2644,1242,904.0
13,637.0,829.0,1597,1732,1643,2021,1756,801,450.0
14,749.0,978.0,1922,2131,2151,2318,1964,825,376.0
15,913.0,1520.0,2735,2596,3061,3554,2791,1186,571.0
16,910.0,1469.0,2884,2837,3070,3253,2515,985,406.0
17,959.0,1346.0,3062,2780,3087,2938,1771,515,165.0
18,2479.0,4335.0,9890,6967,7308,6810,2591,713,279.0
19,3424.0,5541.0,12236,8925,8353,8237,4364,1364,629.0
20,3874.0,5964.0,13556,11266,10157,7223,4982,1923,906.0
21,4207.0,6855.0,8963,9008,7936,5822,6117,2748,1751.0
22,7214.0,9525.0,7450,10213,9726,10338,15516,7760,4757.0
23,20783.0,19474.0,18184,23245,24414,24350,33198,13582,6285.0
24,25542.0,35769.0,43080,32855,33524,22340,13272,4742,3556.0
25,297636.0,329742.0,394189,348856,369683,257524,175967,68443,45806.0
26,1279285.0,1352696.0,1390640,1463168,1533008,1201246,997873,461844,279610.0
27,448522.0,481777.0,554366,601973,639868,546779,468720,248930,151160.0
28,74973.0,108245.0,147723,122847,126999,114821,91553,49269,29484.0
29,20629.0,32193.0,55015,39343,37247,32572,22896,10240,5445.0
30,125286.0,200684.0,260737,215638,214643,181020,126705,60949,30301.0
31,295667.0,372182.0,526134,496001,510309,495779,417446,229642,126727.0
32,130031.0,192161.0,195593,203492,223579,207778,191533,112508,66046.0
33,54166.0,94171.0,100544,109425,116301,111750,103100,61356,37608.0
34,97997.0,174410.0,205416,219729,230072,221634,198906,115754,77400.0
35,117836.0,229013.0,268421,296395,301837,287658,242678,129443,87298.0
36,59399.0,96262.0,158588,171902,171203,167410,148364,85888,58347.0
37,20601.0,28367.0,47981,52832,50101,46981,43966,26998,19470.0
38,17760.0,45567.0,46316,45220,43444,38520,34463,21085,14627.0
39,15503.0,36702.0,51065,56736,51145,46930,46767,29067,19148.0
40,21431.0,61744.0,77476,83275,75658,68542,71734,44984,28503.0
41,22743.0,59677.0,67360,78237,72981,67012,72696,43725,24345.0
42,39774.0,122479.0,131080,145442,145700,132112,137775,86238,49027.0
43,56328.0,130034.0,184949,202606,198037,190991,202496,126479,78436.0

In [57]:
df_population

,Unnamed: 0,year,month,0-9(population),10-19(population),20-29(population),30-39(population),40-49(population),50-59(population),60-69(population),70-79(population),over80(population)
0,0,2020,1,4148654,4940455,6806410,7045120,8389281,8666971,6344284,3607104,1899230
1,1,2020,2,4134824,4920794,6786097,7026850,8397417,8666798,6385073,3612980,1913794
2,2,2020,3,4119475,4902009,6799238,7006749,8375429,8662400,6426006,3623899,1927990
3,3,2020,4,4103848,4887408,6802925,6995799,8362127,8661935,6456674,3632966,1938842
4,4,2020,5,4089462,4872081,6804350,6985248,8346911,8668601,6481317,3646121,1947280
5,5,2020,6,4075794,4861506,6803579,6972185,8342267,8652260,6523322,3658049,1950446
6,6,2020,7,4062274,4850566,6801367,6956361,8338271,8653176,6549914,3671175,1956748
7,7,2020,8,4045950,4838700,6800612,6939804,8330276,8651547,6590179,3676849,1966036
8,8,2020,9,4027765,4828702,6801056,6922566,8321409,8652305,6630461,3680759,1976763
9,9,2020,10,4005030,4818481,6802784,6900752,8312221,8655292,6669780,3687451,1986225
10,10,2020,11,3984472,4807963,6804936,6884029,8305172,8653322,6707084,3693926,1993398
11,11,2020,12,3970070,4793336,6806153,6873117,8294787,8645014,6744506,3698246,2003794
12,12,2021,1,3944244,4784388,6792483,6856414,8285935,8642700,6794549,3707683,2017536
13,13,2021,2,3927428,4772917,6771959,6834586,8287143,8644918,6840597,3710261,2034333
14,14,2021,3,3908794,4761113,6767952,6812701,8250451,8613059,6876287,3694544,2021004
15,15,2021,4,3891405,4753626,6761949,6802386,8244087,8604370,6918145,3693918,2032214
16,16,2021,5,3874174,4746103,6754283,6788072,8220344,8606589,6957802,3694633,2041025
17,17,2021,6,3859229,4741570,6745313,6775108,8216263,8590314,7001815,3694311,2048477
18,18,2021,7,3843759,4737829,6733054,6764334,8205797,8591085,7039371,3699044,2057296
19,19,2021,8,3827185,4733729,6721376,6753189,8192793,8598568,7072000,3703046,2067830
20,20,2021,9,3809849,4727626,6708734,6745531,8182067,8610979,7097818,3705737,2079347
21,21,2021,10,3792548,4721726,6691903,6739933,8169827,8622455,7124259,3710920,2088719
22,22,2021,11,3775503,4716775,6674970,6731509,8165990,8631102,7147578,3712470,2096807
23,23,2021,12,3760350,4709316,6655923,6723435,8166792,8635211,7164712,3715084,2107986
24,24,2022,1,3736642,4706002,6632711,6704271,8166823,8635055,7196303,3724894,2129772
25,25,2022,2,3718850,4702667,6606751,6681507,8172801,8630063,7228356,3736880,2147686
26,26,2022,3,3697734,4699914,6594325,6673424,8157546,8638696,7237134,3749844,2162078
27,27,2022,4,3679892,4697255,6579507,6666711,8153849,8647758,7243664,3755435,2168589
28,28,2022,5,3662692,4695186,6564754,6660669,8142338,8650247,7245254,3783011,2179571
29,29,2022,6,3644574,4696377,6547881,6653299,8141674,8649731,7260782,3795157,2188703
30,30,2022,7,3624681,4696767,6531636,6647003,8134712,8651892,7279621,3807864,2200270
31,31,2022,8,3606212,4698846,6513110,6640555,8122023,8645832,7303567,3815045,2213251
32,32,2022,9,3587171,4700253,6487234,6629383,8099849,8623902,7309977,3813420,2215469
33,33,2022,10,3566622,4703349,6463741,6625319,8088855,8614576,7346707,3814072,2236385
34,34,2022,11,3548291,4704693,6441542,6620713,8083707,8607789,7379420,3818887,2245787
35,35,2022,12,3532642,4703196,6417181,6615511,8073117,8612064,7403539,3825717,2256071
36,36,2023,1,3510756,4702482,6393461,6600252,8065721,8616924,7434333,3835199,2270890
37,37,2023,2,3494655,4697666,6366296,6581804,8068794,8622349,7461127,3840239,2288549
38,38,2023,3,3478290,4690388,6349354,6585469,8047460,8620204,7485540,3855550,2302026
39,39,2023,4,3460142,4684275,6333731,6589037,8027947,8609976,7525051,3865977,2312019
40,40,2023,5,3445285,4679181,6318641,6588734,8007347,8622447,7537569,3883027,2318290
41,41,2023,6,3431910,4676000,6301901,6588552,7998075,8627184,7553882,3894490,2320751
42,42,2023,7,3415119,4674885,6284235,6588036,7988791,8631299,7571631,3907575,2325562
43,43,2023,8,3398415,4673674,6265976,6587136,7977613,8634255,7589676,3918796,2331672

In [58]:
df_rate

,0-9(rate),10-19(rate),20-29(rate),30-39(rate),40-49(rate),50-59(rate),60-69(rate),70-79(rate),over80(rate)
0,0.000000,0.000000,4.407610e-07,2.838844e-07,0.000000,5.769028e-07,1.576222e-07,0.000000,0.000000
1,0.000005,0.000020,1.256982e-04,5.094744e-05,0.000052,6.669130e-05,6.092334e-05,0.000037,0.000028
2,0.000023,0.000085,2.644414e-04,9.319586e-05,0.000105,1.461489e-04,1.314969e-04,0.000143,0.000201
3,0.000007,0.000016,4.365769e-05,2.072672e-05,0.000013,1.235290e-05,1.750127e-05,0.000016,0.000023
4,0.000004,0.000014,3.277315e-05,1.918328e-05,0.000011,9.574786e-06,8.794509e-06,0.000004,0.000007
5,0.000009,0.000010,2.763252e-05,2.925912e-05,0.000019,2.854745e-05,4.031688e-05,0.000034,0.000030
6,0.000013,0.000015,3.793355e-05,4.513854e-05,0.000030,2.692653e-05,2.824465e-05,0.000026,0.000021
7,0.000048,0.000075,1.029319e-04,9.812957e-05,0.000092,1.293410e-04,1.690394e-04,0.000141,0.000096
8,0.000034,0.000033,6.498991e-05,6.023778e-05,0.000058,9.049612e-05,1.227667e-04,0.000120,0.000094
9,0.000028,0.000031,5.982845e-05,5.448682e-05,0.000046,5.210685e-05,6.402010e-05,0.000057,0.000090
10,0.000076,0.000123,1.904500e-04,1.592091e-04,0.000148,1.556628e-04,1.537181e-04,0.000137,0.000143
11,0.000277,0.000359,4.764806e-04,4.868242e-04,0.000461,5.984953e-04,6.501588e-04,0.000580,0.000792
12,0.000226,0.000300,3.290402e-04,3.275765e-04,0.000313,3.797424e-04,3.891355e-04,0.000335,0.000448
13,0.000162,0.000174,2.358254e-04,2.534170e-04,0.000198,2.337790e-04,2.567027e-04,0.000216,0.000221
14,0.000192,0.000205,2.839855e-04,3.127981e-04,0.000261,2.691262e-04,2.856193e-04,0.000223,0.000186
15,0.000235,0.000320,4.044692e-04,3.816308e-04,0.000371,4.130459e-04,4.034318e-04,0.000321,0.000281
16,0.000235,0.000310,4.269883e-04,4.179390e-04,0.000373,3.779662e-04,3.614647e-04,0.000267,0.000199
17,0.000248,0.000284,4.539448e-04,4.103256e-04,0.000376,3.420131e-04,2.529344e-04,0.000139,0.000081
18,0.000645,0.000915,1.468873e-03,1.029961e-03,0.000891,7.926822e-04,3.680727e-04,0.000193,0.000136
19,0.000895,0.001171,1.820461e-03,1.321598e-03,0.001020,9.579502e-04,6.170814e-04,0.000368,0.000304
20,0.001017,0.001262,2.020649e-03,1.670143e-03,0.001241,8.388129e-04,7.019059e-04,0.000519,0.000436
21,0.001109,0.001452,1.339380e-03,1.336512e-03,0.000971,6.752137e-04,8.586156e-04,0.000741,0.000838
22,0.001911,0.002019,1.116110e-03,1.517193e-03,0.001191,1.197761e-03,2.170805e-03,0.002090,0.002269
23,0.005527,0.004135,2.732003e-03,3.457310e-03,0.002989,2.819850e-03,4.633543e-03,0.003656,0.002982
24,0.006836,0.007601,6.495082e-03,4.900607e-03,0.004105,2.587129e-03,1.844280e-03,0.001273,0.001670
25,0.080034,0.070118,5.966458e-02,5.221217e-02,0.045233,2.984034e-02,2.434399e-02,0.018316,0.021328
26,0.345965,0.287813,2.108844e-01,2.192530e-01,0.187925,1.390541e-01,1.378823e-01,0.123164,0.129325
27,0.121885,0.102566,8.425646e-02,9.029535e-02,0.078474,6.322783e-02,6.470758e-02,0.066285,0.069704
28,0.020469,0.023054,2.250244e-02,1.844364e-02,0.015597,1.327373e-02,1.263627e-02,0.013024,0.013527
29,0.005660,0.006855,8.401955e-03,5.913307e-03,0.004575,3.765666e-03,3.153379e-03,0.002698,0.002488
30,0.034565,0.042728,3.991910e-02,3.244139e-02,0.026386,2.092259e-02,1.740544e-02,0.016006,0.013771
31,0.081988,0.079207,8.078076e-02,7.469270e-02,0.062830,5.734312e-02,5.715646e-02,0.060194,0.057258
32,0.036249,0.040883,3.015045e-02,3.069547e-02,0.027603,2.409327e-02,2.620159e-02,0.029503,0.029811
33,0.015187,0.020022,1.555508e-02,1.651619e-02,0.014378,1.297220e-02,1.403350e-02,0.016087,0.016816
34,0.027618,0.037071,3.188926e-02,3.318812e-02,0.028461,2.574808e-02,2.695415e-02,0.030311,0.034465
35,0.033356,0.048693,4.182849e-02,4.480304e-02,0.037388,3.340175e-02,3.277865e-02,0.033835,0.038695
36,0.016919,0.020470,2.480472e-02,2.604476e-02,0.021226,1.942805e-02,1.995660e-02,0.022395,0.025693
37,0.005895,0.006039,7.536722e-03,8.026979e-03,0.006209,5.448747e-03,5.892675e-03,0.007030,0.008508
38,0.005106,0.009715,7.294600e-03,6.866633e-03,0.005398,4.468572e-03,4.603943e-03,0.005469,0.006354
39,0.004480,0.007835,8.062389e-03,8.610666e-03,0.006371,5.450654e-03,6.214842e-03,0.007519,0.008282
40,0.006220,0.013195,1.226150e-02,1.263900e-02,0.009449,7.949252e-03,9.516861e-03,0.011585,0.012295
41,0.006627,0.012762,1.068884e-02,1.187469e-02,0.009125,7.767540e-03,9.623661e-03,0.011227,0.010490
42,0.011646,0.026199,2.085855e-02,2.207669e-02,0.018238,1.530615e-02,1.819621e-02,0.022069,0.021082
43,0.016575,0.027823,2.951639e-02,3.075783e-02,0.024824,2.212015e-02,2.668045e-02,0.032275,0.033639

In [59]:
df = pd.concat([df_population, df_confirmed, df_rate], axis=1)
df

,Unnamed: 0,year,month,0-9(population),10-19(population),20-29(population),30-39(population),40-49(population),50-59(population),60-69(population),...,over80(confirmed_case),0-9(rate),10-19(rate),20-29(rate),30-39(rate),40-49(rate),50-59(rate),60-69(rate),70-79(rate),over80(rate)
0,0,2020,1,4148654,4940455,6806410,7045120,8389281,8666971,6344284,...,0.0,0.000000,0.000000,4.407610e-07,2.838844e-07,0.000000,5.769028e-07,1.576222e-07,0.000000,0.000000
1,1,2020,2,4134824,4920794,6786097,7026850,8397417,8666798,6385073,...,54.0,0.000005,0.000020,1.256982e-04,5.094744e-05,0.000052,6.669130e-05,6.092334e-05,0.000037,0.000028
2,2,2020,3,4119475,4902009,6799238,7006749,8375429,8662400,6426006,...,387.0,0.000023,0.000085,2.644414e-04,9.319586e-05,0.000105,1.461489e-04,1.314969e-04,0.000143,0.000201
3,3,2020,4,4103848,4887408,6802925,6995799,8362127,8661935,6456674,...,44.0,0.000007,0.000016,4.365769e-05,2.072672e-05,0.000013,1.235290e-05,1.750127e-05,0.000016,0.000023
4,4,2020,5,4089462,4872081,6804350,6985248,8346911,8668601,6481317,...,13.0,0.000004,0.000014,3.277315e-05,1.918328e-05,0.000011,9.574786e-06,8.794509e-06,0.000004,0.000007
5,5,2020,6,4075794,4861506,6803579,6972185,8342267,8652260,6523322,...,58.0,0.000009,0.000010,2.763252e-05,2.925912e-05,0.000019,2.854745e-05,4.031688e-05,0.000034,0.000030
6,6,2020,7,4062274,4850566,6801367,6956361,8338271,8653176,6549914,...,42.0,0.000013,0.000015,3.793355e-05,4.513854e-05,0.000030,2.692653e-05,2.824465e-05,0.000026,0.000021
7,7,2020,8,4045950,4838700,6800612,6939804,8330276,8651547,6590179,...,188.0,0.000048,0.000075,1.029319e-04,9.812957e-05,0.000092,1.293410e-04,1.690394e-04,0.000141,0.000096
8,8,2020,9,4027765,4828702,6801056,6922566,8321409,8652305,6630461,...,185.0,0.000034,0.000033,6.498991e-05,6.023778e-05,0.000058,9.049612e-05,1.227667e-04,0.000120,0.000094
9,9,2020,10,4005030,4818481,6802784,6900752,8312221,8655292,6669780,...,179.0,0.000028,0.000031,5.982845e-05,5.448682e-05,0.000046,5.210685e-05,6.402010e-05,0.000057,0.000090
10,10,2020,11,3984472,4807963,6804936,6884029,8305172,8653322,6707084,...,285.0,0.000076,0.000123,1.904500e-04,1.592091e-04,0.000148,1.556628e-04,1.537181e-04,0.000137,0.000143
11,11,2020,12,3970070,4793336,6806153,6873117,8294787,8645014,6744506,...,1587.0,0.000277,0.000359,4.764806e-04,4.868242e-04,0.000461,5.984953e-04,6.501588e-04,0.000580,0.000792
12,12,2021,1,3944244,4784388,6792483,6856414,8285935,8642700,6794549,...,904.0,0.000226,0.000300,3.290402e-04,3.275765e-04,0.000313,3.797424e-04,3.891355e-04,0.000335,0.000448
13,13,2021,2,3927428,4772917,6771959,6834586,8287143,8644918,6840597,...,450.0,0.000162,0.000174,2.358254e-04,2.534170e-04,0.000198,2.337790e-04,2.567027e-04,0.000216,0.000221
14,14,2021,3,3908794,4761113,6767952,6812701,8250451,8613059,6876287,...,376.0,0.000192,0.000205,2.839855e-04,3.127981e-04,0.000261,2.691262e-04,2.856193e-04,0.000223,0.000186
15,15,2021,4,3891405,4753626,6761949,6802386,8244087,8604370,6918145,...,571.0,0.000235,0.000320,4.044692e-04,3.816308e-04,0.000371,4.130459e-04,4.034318e-04,0.000321,0.000281
16,16,2021,5,3874174,4746103,6754283,6788072,8220344,8606589,6957802,...,406.0,0.000235,0.000310,4.269883e-04,4.179390e-04,0.000373,3.779662e-04,3.614647e-04,0.000267,0.000199
17,17,2021,6,3859229,4741570,6745313,6775108,8216263,8590314,7001815,...,165.0,0.000248,0.000284,4.539448e-04,4.103256e-04,0.000376,3.420131e-04,2.529344e-04,0.000139,0.000081
18,18,2021,7,3843759,4737829,6733054,6764334,8205797,8591085,7039371,...,279.0,0.000645,0.000915,1.468873e-03,1.029961e-03,0.000891,7.926822e-04,3.680727e-04,0.000193,0.000136
19,19,2021,8,3827185,4733729,6721376,6753189,8192793,8598568,7072000,...,629.0,0.000895,0.001171,1.820461e-03,1.321598e-03,0.001020,9.579502e-04,6.170814e-04,0.000368,0.000304
20,20,2021,9,3809849,4727626,6708734,6745531,8182067,8610979,7097818,...,906.0,0.001017,0.001262,2.020649e-03,1.670143e-03,0.001241,8.388129e-04,7.019059e-04,0.000519,0.000436
21,21,2021,10,3792548,4721726,6691903,6739933,8169827,8622455,7124259,...,1751.0,0.001109,0.001452,1.339380e-03,1.336512e-03,0.000971,6.752137e-04,8.586156e-04,0.000741,0.000838
22,22,2021,11,3775503,4716775,6674970,6731509,8165990,8631102,7147578,...,4757.0,0.001911,0.002019,1.116110e-03,1.517193e-03,0.001191,1.197761e-03,2.170805e-03,0.002090,0.002269
23,23,2021,12,3760350,4709316,6655923,6723435,8166792,8635211,7164712,...,6285.0,0.005527,0.004135,2.732003e-03,3.457310e-03,0.002989,2.819850e-03,4.633543e-03,0.003656,0.002982
24,24,2022,1,3736642,4706002,6632711,6704271,8166823,8635055,7196303,...,3556.0,0.006836,0.007601,6.495082e-03,4.900607e-03,0.004105,2.587129e-03,1.844280e-03,0.001273,0.001670
25,25,2022,2,3718850,4702667,6606751,6681507,8172801,8630063,7228356,...,45806.0,0.080034,0.070118,5.966458e-02,5.221217e-02,0.045233,2.984034e-02,2.434399e-02,0.018316,0.021328
26,26,2022,3,3697734,4699914,6594325,6673424,8157546,8638696,7237134,...,279610.0,0.345965,0.287813,2.108844e-01,2.192530e-01,0.187925,1.390541e-01,1.378823e-01,0.123164,0.129325
27,27,2022,4,3679892,4697255,6579507,6666711,8153849,8647758,7243664,...,151160.0,0.121885,0.102566,8.425646e-02,9.029535e-02,0.078474,6.322783e-02,6.470758e-02,0.066285,0.069704
28,28,2022,5,3662692,4695186,6564754,6660669,8142338,8650247,7245254,...,29484.0,0.020469,0.023054,2.250244e-02,1.844364e-02,0.015597,1.327373e-02,1.263627e-02,0.013024,0.013527
29,29,2022,6,3644574,4696377,6547881,6653299,8141674,8649731,7260782,...,5445.0,0.005660,0.006855,8.401955e-03,5.913307e-03,0.004575,3.765666e-03,3.153379e-03,0.002698,0.002488
30,30,2022,7,3624681,4696767,6531636,6647003,8134712,8651892,7279621,...,30301.0,0.034565,0.042728,3.991910e-02,3.244139e-02,0.026386,2.092259e-02,1.740544e-02,0.016006,0.013771
31,31,2022,8,3606212,4698846,6513110,6640555,8122023,8645832,7303567,...,126727.0,0.081988,0.079207,8.078076e-02,7.469270e-02,0.062830,5.734312e-02,5.715646e-02,0.060194,0.057258
32,32,2022,9,3587171,4700253,6487234,6629383,8099849,8623902,7309977,...,66046.0,0.036249,0.040883,3.015045e-02,3.069547e-02,0.027603,2.409327e-02,2.620159e-02,0.029503,0.029811
33,33,2022,10,3566622,4703349,6463741,6625319,8088855,8614576,7346707,...,37608.0,0.015187,0.020022,1.555508e-02,1.651619e-02,0.014378,1.297220e-02,1.403350e-02,0.016087,0.016816
34,34,2022,11,3548291,4704693,6441542,6620713,8083707,8607789,7379420,...,77400.0,0.027618,0.037071,3.188926e-02,3.318812e-02,0.028461,2.574808e-02,2.695415e-02,0.030311,0.034465
35,35,2022,12,3532642,4703196,6417181,6615511,8073117,8612064,7403539,...,87298.0,0.033356,0.048693,4.182849e-02,4.480304e-02,0.037388,3.340175e-02,3.277865e-02,0.033835,0.038695
36,36,2023,1,3510756,4702482,6393461,6600252,8065721,8616924,7434333,...,58347.0,0.016919,0.020470,2.480472e-02,2.604476e-02,0.021226,1.942805e-02,1.995660e-02,0.022395,0.025693
37,37,2023,2,3494655,4697666,6366296,6581804,8068794,8622349,7461127,...,19470.0,0.005895,0.006039,7.536722e-03,8.026979e-03,0.006209,5.448747e-03,5.892675e-03,0.007030,0.008508
38,38,2023,3,3478290,4690388,6349354,6585469,8047460,8620204,7485540,...,14627.0,0.005106,0.009715,7.294600e-03,6.866633e-03,0.005398,4.468572e-03,4.603943e-03,0.005469,0.006354
39,39,2023,4,3460142,4684275,6333731,6589037,8027947,8609976,7525051,...,19148.0,0.004480,0.007835,8.062389e-03,8.610666e-03,0.006371,5.450654e-03,6.214842e-03,0.007519,0.008282
40,40,2023,5,3445285,4679181,6318641,6588734,8007347,8622447,7537569,...,28503.0,0.006220,0.013195,1.226150e-02,1.263900e-02,0.009449,7.949252e-03,9.516861e-03,0.011585,0.012295
41,41,2023,6,3431910,4676000,6301901,6588552,7998075,8627184,7553882,...,24345.0,0.006627,0.012762,1.068884e-02,1.187469e-02,0.009125,7.767540e-03,9.623661e-03,0.011227,0.010490
42,42,2023,7,3415119,4674885,6284235,6588036,7988791,8631299,7571631,...,49027.0,0.011646,0.026199,2.085855e-02,2.207669e-02,0.018238,1.530615e-02,1.819621e-02,0.022069,0.021082
43,43,2023,8,3398415,4673674,6265976,6587136,7977613,8634255,7589676,...,78436.0,0.016575,0.027823,2.951639e-02,3.075783e-02,0.024824,2.212015e-02,2.668045e-02,0.032275,0.033639

In [60]:
df.sort_index(axis =1, ascending=True, inplace =  True)

In [61]:
df

,0-9(confirmed_case),0-9(population),0-9(rate),10-19(confirmed_case),10-19(population),10-19(rate),20-29(confirmed_case),20-29(population),20-29(rate),30-39(confirmed_case),...,60-69(rate),70-79(confirmed_case),70-79(population),70-79(rate),Unnamed: 0,month,over80(confirmed_case),over80(population),over80(rate),year
0,0.0,4148654,0.000000,0.0,4940455,0.000000,3,6806410,4.407610e-07,2,...,1.576222e-07,0,3607104,0.000000,0,1,0.0,1899230,0.000000,2020
1,19.0,4134824,0.000005,99.0,4920794,0.000020,853,6786097,1.256982e-04,358,...,6.092334e-05,133,3612980,0.000037,1,2,54.0,1913794,0.000028,2020
2,94.0,4119475,0.000023,416.0,4902009,0.000085,1798,6799238,2.644414e-04,653,...,1.314969e-04,518,3623899,0.000143,2,3,387.0,1927990,0.000201,2020
3,27.0,4103848,0.000007,76.0,4887408,0.000016,297,6802925,4.365769e-05,145,...,1.750127e-05,58,3632966,0.000016,3,4,44.0,1938842,0.000023,2020
4,17.0,4089462,0.000004,66.0,4872081,0.000014,223,6804350,3.277315e-05,134,...,8.794509e-06,16,3646121,0.000004,4,5,13.0,1947280,0.000007,2020
5,35.0,4075794,0.000009,51.0,4861506,0.000010,188,6803579,2.763252e-05,204,...,4.031688e-05,125,3658049,0.000034,5,6,58.0,1950446,0.000030,2020
6,54.0,4062274,0.000013,74.0,4850566,0.000015,258,6801367,3.793355e-05,314,...,2.824465e-05,97,3671175,0.000026,6,7,42.0,1956748,0.000021,2020
7,196.0,4045950,0.000048,363.0,4838700,0.000075,700,6800612,1.029319e-04,681,...,1.690394e-04,517,3676849,0.000141,7,8,188.0,1966036,0.000096,2020
8,136.0,4027765,0.000034,161.0,4828702,0.000033,442,6801056,6.498991e-05,417,...,1.227667e-04,442,3680759,0.000120,8,9,185.0,1976763,0.000094,2020
9,114.0,4005030,0.000028,151.0,4818481,0.000031,407,6802784,5.982845e-05,376,...,6.402010e-05,210,3687451,0.000057,9,10,179.0,1986225,0.000090,2020
10,301.0,3984472,0.000076,592.0,4807963,0.000123,1296,6804936,1.904500e-04,1096,...,1.537181e-04,507,3693926,0.000137,10,11,285.0,1993398,0.000143,2020
11,1098.0,3970070,0.000277,1720.0,4793336,0.000359,3243,6806153,4.764806e-04,3346,...,6.501588e-04,2145,3698246,0.000580,11,12,1587.0,2003794,0.000792,2020
12,893.0,3944244,0.000226,1433.0,4784388,0.000300,2235,6792483,3.290402e-04,2246,...,3.891355e-04,1242,3707683,0.000335,12,1,904.0,2017536,0.000448,2021
13,637.0,3927428,0.000162,829.0,4772917,0.000174,1597,6771959,2.358254e-04,1732,...,2.567027e-04,801,3710261,0.000216,13,2,450.0,2034333,0.000221,2021
14,749.0,3908794,0.000192,978.0,4761113,0.000205,1922,6767952,2.839855e-04,2131,...,2.856193e-04,825,3694544,0.000223,14,3,376.0,2021004,0.000186,2021
15,913.0,3891405,0.000235,1520.0,4753626,0.000320,2735,6761949,4.044692e-04,2596,...,4.034318e-04,1186,3693918,0.000321,15,4,571.0,2032214,0.000281,2021
16,910.0,3874174,0.000235,1469.0,4746103,0.000310,2884,6754283,4.269883e-04,2837,...,3.614647e-04,985,3694633,0.000267,16,5,406.0,2041025,0.000199,2021
17,959.0,3859229,0.000248,1346.0,4741570,0.000284,3062,6745313,4.539448e-04,2780,...,2.529344e-04,515,3694311,0.000139,17,6,165.0,2048477,0.000081,2021
18,2479.0,3843759,0.000645,4335.0,4737829,0.000915,9890,6733054,1.468873e-03,6967,...,3.680727e-04,713,3699044,0.000193,18,7,279.0,2057296,0.000136,2021
19,3424.0,3827185,0.000895,5541.0,4733729,0.001171,12236,6721376,1.820461e-03,8925,...,6.170814e-04,1364,3703046,0.000368,19,8,629.0,2067830,0.000304,2021
20,3874.0,3809849,0.001017,5964.0,4727626,0.001262,13556,6708734,2.020649e-03,11266,...,7.019059e-04,1923,3705737,0.000519,20,9,906.0,2079347,0.000436,2021
21,4207.0,3792548,0.001109,6855.0,4721726,0.001452,8963,6691903,1.339380e-03,9008,...,8.586156e-04,2748,3710920,0.000741,21,10,1751.0,2088719,0.000838,2021
22,7214.0,3775503,0.001911,9525.0,4716775,0.002019,7450,6674970,1.116110e-03,10213,...,2.170805e-03,7760,3712470,0.002090,22,11,4757.0,2096807,0.002269,2021
23,20783.0,3760350,0.005527,19474.0,4709316,0.004135,18184,6655923,2.732003e-03,23245,...,4.633543e-03,13582,3715084,0.003656,23,12,6285.0,2107986,0.002982,2021
24,25542.0,3736642,0.006836,35769.0,4706002,0.007601,43080,6632711,6.495082e-03,32855,...,1.844280e-03,4742,3724894,0.001273,24,1,3556.0,2129772,0.001670,2022
25,297636.0,3718850,0.080034,329742.0,4702667,0.070118,394189,6606751,5.966458e-02,348856,...,2.434399e-02,68443,3736880,0.018316,25,2,45806.0,2147686,0.021328,2022
26,1279285.0,3697734,0.345965,1352696.0,4699914,0.287813,1390640,6594325,2.108844e-01,1463168,...,1.378823e-01,461844,3749844,0.123164,26,3,279610.0,2162078,0.129325,2022
27,448522.0,3679892,0.121885,481777.0,4697255,0.102566,554366,6579507,8.425646e-02,601973,...,6.470758e-02,248930,3755435,0.066285,27,4,151160.0,2168589,0.069704,2022
28,74973.0,3662692,0.020469,108245.0,4695186,0.023054,147723,6564754,2.250244e-02,122847,...,1.263627e-02,49269,3783011,0.013024,28,5,29484.0,2179571,0.013527,2022
29,20629.0,3644574,0.005660,32193.0,4696377,0.006855,55015,6547881,8.401955e-03,39343,...,3.153379e-03,10240,3795157,0.002698,29,6,5445.0,2188703,0.002488,2022
30,125286.0,3624681,0.034565,200684.0,4696767,0.042728,260737,6531636,3.991910e-02,215638,...,1.740544e-02,60949,3807864,0.016006,30,7,30301.0,2200270,0.013771,2022
31,295667.0,3606212,0.081988,372182.0,4698846,0.079207,526134,6513110,8.078076e-02,496001,...,5.715646e-02,229642,3815045,0.060194,31,8,126727.0,2213251,0.057258,2022
32,130031.0,3587171,0.036249,192161.0,4700253,0.040883,195593,6487234,3.015045e-02,203492,...,2.620159e-02,112508,3813420,0.029503,32,9,66046.0,2215469,0.029811,2022
33,54166.0,3566622,0.015187,94171.0,4703349,0.020022,100544,6463741,1.555508e-02,109425,...,1.403350e-02,61356,3814072,0.016087,33,10,37608.0,2236385,0.016816,2022
34,97997.0,3548291,0.027618,174410.0,4704693,0.037071,205416,6441542,3.188926e-02,219729,...,2.695415e-02,115754,3818887,0.030311,34,11,77400.0,2245787,0.034465,2022
35,117836.0,3532642,0.033356,229013.0,4703196,0.048693,268421,6417181,4.182849e-02,296395,...,3.277865e-02,129443,3825717,0.033835,35,12,87298.0,2256071,0.038695,2022
36,59399.0,3510756,0.016919,96262.0,4702482,0.020470,158588,6393461,2.480472e-02,171902,...,1.995660e-02,85888,3835199,0.022395,36,1,58347.0,2270890,0.025693,2023
37,20601.0,3494655,0.005895,28367.0,4697666,0.006039,47981,6366296,7.536722e-03,52832,...,5.892675e-03,26998,3840239,0.007030,37,2,19470.0,2288549,0.008508,2023
38,17760.0,3478290,0.005106,45567.0,4690388,0.009715,46316,6349354,7.294600e-03,45220,...,4.603943e-03,21085,3855550,0.005469,38,3,14627.0,2302026,0.006354,2023
39,15503.0,3460142,0.004480,36702.0,4684275,0.007835,51065,6333731,8.062389e-03,56736,...,6.214842e-03,29067,3865977,0.007519,39,4,19148.0,2312019,0.008282,2023
40,21431.0,3445285,0.006220,61744.0,4679181,0.013195,77476,6318641,1.226150e-02,83275,...,9.516861e-03,44984,3883027,0.011585,40,5,28503.0,2318290,0.012295,2023
41,22743.0,3431910,0.006627,59677.0,4676000,0.012762,67360,6301901,1.068884e-02,78237,...,9.623661e-03,43725,3894490,0.011227,41,6,24345.0,2320751,0.010490,2023
42,39774.0,3415119,0.011646,122479.0,4674885,0.026199,131080,6284235,2.085855e-02,145442,...,1.819621e-02,86238,3907575,0.022069,42,7,49027.0,2325562,0.021082,2023
43,56328.0,3398415,0.016575,130034.0,4673674,0.027823,184949,6265976,2.951639e-02,202606,...,2.668045e-02,126479,3918796,0.032275,43,8,78436.0,2331672,0.033639,2023

In [62]:
df.columns

Index(['0-9(confirmed_case)', '0-9(population)', '0-9(rate)',
       '10-19(confirmed_case)', '10-19(population)', '10-19(rate)',
       '20-29(confirmed_case)', '20-29(population)', '20-29(rate)',
       '30-39(confirmed_case)', '30-39(population)', '30-39(rate)',
       '40-49(confirmed_case)', '40-49(population)', '40-49(rate)',
       '50-59(confirmed_case)', '50-59(population)', '50-59(rate)',
       '60-69(confirmed_case)', '60-69(population)', '60-69(rate)',
       '70-79(confirmed_case)', '70-79(population)', '70-79(rate)',
       'Unnamed: 0', 'month', 'over80(confirmed_case)', 'over80(population)',
       'over80(rate)', 'year'],
      dtype='object')

In [63]:
df_final=df[['year', 'month', 
             '0-9(population)', '0-9(confirmed_case)', '0-9(rate)',
            '10-19(population)', '10-19(confirmed_case)', '10-19(rate)',
            '20-29(population)', '20-29(confirmed_case)', '20-29(rate)',
            '30-39(population)', '30-39(confirmed_case)', '30-39(rate)',
            '40-49(population)', '40-49(confirmed_case)', '40-49(rate)',
            '50-59(population)', '50-59(confirmed_case)', '50-59(rate)',
            '60-69(population)', '60-69(confirmed_case)', '60-69(rate)',
            '70-79(population)', '70-79(confirmed_case)', '70-79(rate)',
            'over80(population)', 'over80(confirmed_case)', 'over80(rate)']]

In [66]:
df_final.to_csv('df_final.csv')